# Generated by Django 2.1.7 on 2019-02-18 01:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('invite', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('mutual_contacts', models.IntegerField(default=0)),
                ('picture', models.URLField(null=True)),
                ('position', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
