# Generated by Django 2.1.7 on 2019-02-28 19:30

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageDistribution',
            fields=[
                ('id', models.CharField(default=uuid.uuid1, max_length=255, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('send', models.ManyToManyField(blank=True, to='core.Contact')),
            ],
        ),
    ]
